// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/blog/taxonomy.proto

package blog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaxonomyType int32

const (
	TaxonomyType_Category TaxonomyType = 0
	TaxonomyType_Tag      TaxonomyType = 1
)

// Enum value maps for TaxonomyType.
var (
	TaxonomyType_name = map[int32]string{
		0: "Category",
		1: "Tag",
	}
	TaxonomyType_value = map[string]int32{
		"Category": 0,
		"Tag":      1,
	}
)

func (x TaxonomyType) Enum() *TaxonomyType {
	p := new(TaxonomyType)
	*p = x
	return p
}

func (x TaxonomyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxonomyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_blog_taxonomy_proto_enumTypes[0].Descriptor()
}

func (TaxonomyType) Type() protoreflect.EnumType {
	return &file_proto_blog_taxonomy_proto_enumTypes[0]
}

func (x TaxonomyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxonomyType.Descriptor instead.
func (TaxonomyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_blog_taxonomy_proto_rawDescGZIP(), []int{0}
}

// Label attached to the post for the purpose of identification or classification.
type Taxonomy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the taxonomy
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the taxonomy
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Valid url string composes with name and id
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// Type of the term e.g. category or tag
	Type TaxonomyType `protobuf:"varint,4,opt,name=type,proto3,enum=myblog.proto.blog.TaxonomyType" json:"type,omitempty"`
}

func (x *Taxonomy) Reset() {
	*x = Taxonomy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_taxonomy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Taxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taxonomy) ProtoMessage() {}

func (x *Taxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_taxonomy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taxonomy.ProtoReflect.Descriptor instead.
func (*Taxonomy) Descriptor() ([]byte, []int) {
	return file_proto_blog_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *Taxonomy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Taxonomy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Taxonomy) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Taxonomy) GetType() TaxonomyType {
	if x != nil {
		return x.Type
	}
	return TaxonomyType_Category
}

var File_proto_blog_taxonomy_proto protoreflect.FileDescriptor

var file_proto_blog_taxonomy_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x74, 0x61, 0x78,
	0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6d, 0x79, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x22, 0x77,
	0x0a, 0x08, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1f, 0x2e, 0x6d, 0x79, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x25, 0x0a, 0x0c, 0x54, 0x61, 0x78, 0x6f, 0x6e,
	0x6f, 0x6d, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x10, 0x01, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d,
	0x6b, 0x68, 0x6f, 0x6e, 0x77, 0x61, 0x61, 0x6e, 0x2f, 0x6d, 0x79, 0x62, 0x6c, 0x6f, 0x67, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_blog_taxonomy_proto_rawDescOnce sync.Once
	file_proto_blog_taxonomy_proto_rawDescData = file_proto_blog_taxonomy_proto_rawDesc
)

func file_proto_blog_taxonomy_proto_rawDescGZIP() []byte {
	file_proto_blog_taxonomy_proto_rawDescOnce.Do(func() {
		file_proto_blog_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_blog_taxonomy_proto_rawDescData)
	})
	return file_proto_blog_taxonomy_proto_rawDescData
}

var file_proto_blog_taxonomy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_blog_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_blog_taxonomy_proto_goTypes = []interface{}{
	(TaxonomyType)(0), // 0: myblog.proto.blog.TaxonomyType
	(*Taxonomy)(nil),  // 1: myblog.proto.blog.Taxonomy
}
var file_proto_blog_taxonomy_proto_depIdxs = []int32{
	0, // 0: myblog.proto.blog.Taxonomy.type:type_name -> myblog.proto.blog.TaxonomyType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_blog_taxonomy_proto_init() }
func file_proto_blog_taxonomy_proto_init() {
	if File_proto_blog_taxonomy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_blog_taxonomy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Taxonomy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_blog_taxonomy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_blog_taxonomy_proto_goTypes,
		DependencyIndexes: file_proto_blog_taxonomy_proto_depIdxs,
		EnumInfos:         file_proto_blog_taxonomy_proto_enumTypes,
		MessageInfos:      file_proto_blog_taxonomy_proto_msgTypes,
	}.Build()
	File_proto_blog_taxonomy_proto = out.File
	file_proto_blog_taxonomy_proto_rawDesc = nil
	file_proto_blog_taxonomy_proto_goTypes = nil
	file_proto_blog_taxonomy_proto_depIdxs = nil
}
